### ISSUE TITLE
ul . latest-videos-list margin-top ni olib tashlang

### ISSUE THREAD

**Issue by Azizbek-Boyhamdamov** [frontendoniyorbek/exercise-bg-pseudelement#1]
ul.latest-videos-top ni olib tashlang , garchi margin collapse bo'lib halaqit bermayotgan bolsada olib tashlaganiz ma'qul

**Comment by frontendoniyorbek** [comment]
undey qilsam

**Comment by frontendoniyorbek** [comment]
https://prnt.sc/nk6ovlV-cBzF 
shunaqa bo`lib qoladida
