### ISSUE TITLE
ortiqcha

### ISSUE THREAD

**Issue by IbragimovOlimjon** [frontendoniyorbek/exercise-bg-pseudelement#3]
![image](https://user-images.githubusercontent.com/98340831/158435033-da8a25c2-f842-4543-b5f5-f2acf79c939c.png)
biz hali js amallarini qo'llamaganimiz uchun ushbu amallar hozirda saytimizga ortiqcha hisoblanadi

**Comment by frontendoniyorbek** [comment]
hop
